name: flutter_ble_sample
description: "A simple Flutter app demonstrating Bluetooth Low Energy (BLE) functionality."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.17

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true